{{- if or .Values.readinessProbe.enabled .Values.livenessProbe.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "proxysql.fullname" . }}-healthcheck
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
data: 
  PROXYSQL_HEALTHCHECK_DB_USER: {{ .Values.proxysql_cluster.healthcheck.psql_user | default .Values.mysql_variables.monitor_username | quote }}
  PROXYSQL_HEALTHCHECK_DB_HOST: {{ .Values.proxysql_cluster.healthcheck.psql_host | quote }}
  PROXYSQL_HEALTHCHECK_DB_PORT: {{ .Values.proxysql_cluster.healthcheck.psql_host_port | default .Values.service.adminPort | quote }}
  PROXYSQL_HEALTHCHECK_DIFF_CHECK_LIMIT: {{ .Values.proxysql_cluster.healthcheck.diff_check_limit | quote }}
  PROXYSQL_HEALTHCHECK_KILL_IF_HEALTCHECK_FAILED: {{ .Values.proxysql_cluster.healthcheck.kill_if_healthcheck_failed | quote }}
  PROXYSQL_HEALTHCHECK_VERBOSE: {{ .Values.proxysql_cluster.healthcheck.verbose | quote }}
{{- end }}
