{{- if or .Values.readinessProbe.enabled .Values.livenessProbe.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxysql.fullname" . }}-healthcheck
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
data:
  PROXYSQL_HEALTHCHECK_DB_PASS: {{ .Values.proxysql_cluster.healthcheck.psql_pass | default .Values.mysql_variables.monitor_password | default "" | b64enc | quote }}
{{- end }}
