{{- with .Values.services.authrpc }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth.fullname" $ }}-authrpc
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    service-type: authrpc
    {{- include "geth.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - name: authrpc
      port: {{ .port }}
      targetPort: authrpc
  selector:
    {{- include "geth.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
