{{- with .Values.services.p2p }}
{{- if and .enabled (not $.Values.config.node.p2p.useHostPort) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth.fullname" $ }}-p2p
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    service-type: p2p
    {{- include "geth.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - name: p2p-tcp
      port: {{ .port }}
      targetPort: p2p-tcp
      protocol: TCP
      {{- with .nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "geth.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
