{{- if .Values.autoScaleHelper.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bsc.scaleHelperrName" . }}
  labels: {{ include "bsc.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bsc.scaleHelperrName" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bsc.scaleHelperrName" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        bsc/role: "auto-scale-helper"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bsc.serviceAccountName" . }}
      containers:
        - name: helper
          image: {{ .Values.autoScaleHelper.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: scripts
              mountPath: /hooks/controller-hook.sh
              subPath: controller-hook.sh
          resources:
            requests:
              cpu: 10m
              memory: 32M
            limits:
              cpu: 100m
              memory: 128M
      volumes:
        - name: scripts
          configMap:
            name: "{{ .Release.Name }}-scripts"
            defaultMode: 0755
      {{- with .Values.autoScaleHelper.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.autoScaleHelper.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.autoScaleHelper.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
