{{- $fullName := include "bsc.fullname" . -}}
{{- if .Values.ingress.rpc.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-jsonrpc
  labels: {{ include "bsc.labels" . | nindent 4 }}
  {{- with .Values.ingress.rpc.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.rpc.rules.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}
            port:
              name: {{ .Values.service.rpcPortName }}
        path: /
        pathType: ImplementationSpecific
  tls:
  {{- with .Values.ingress.rpc.tls }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
{{- if .Values.ingress.ws.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-wss
  labels:
{{ include "bsc.labels" . | indent 4 }}
  {{- with .Values.ingress.ws.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.ws.rules.host }}
    http:
      paths:
      - backend:
          service:
            name: {{ $.Release.Name }}
            port:
              name: {{ $.Values.service.wsPortName }}
        path: /
        pathType: ImplementationSpecific
  tls:
  {{- with .Values.ingress.ws.tls }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
