{{- if .Values.multicluster.enabled }}
apiVersion: networking.gke.io/v1
kind: MultiClusterIngress
metadata:
  name: {{ .Release.Name }}
  labels: {{ include "bsc.labels" . | nindent 4 }}
  {{- if .Values.multicluster.ingress.ip }}
  annotations:
    networking.gke.io/static-ip: {{ .Values.multicluster.ingress.ip }}
  {{- end }}
spec:
  template:
    spec:
      backend:
        serviceName: {{ .Release.Name }}
        servicePort: {{ .Values.multicluster.service.port }}
{{- end }}
