{{- if .Values.multicluster.enabled }}
apiVersion: networking.gke.io/v1
kind: MultiClusterService
metadata:
  name: {{ .Release.Name }}
  {{- if and .Values.multicluster.enabled .Values.multicluster.backend.sessionAffinity }}
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"{{ .Values.multicluster.service.port }}":"{{ .Release.Name }}"}}'
  {{- end }}
  labels: {{ include "bsc.labels" . | nindent 4 }}
spec:
  template:
    spec:
      selector:
        app.kubernetes.io/name: {{ include "bsc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      ports:
        - name: jsonrpc
          protocol: TCP
          port: {{ .Values.multicluster.service.port }}
          {{- if .Values.failback.enabled }}
          targetPort: {{ .Values.failback.port }}
          {{- else }}
          targetPort: {{ .Values.service.rpcPort }}
          {{- end }}
{{- end }}
