{{- if .Values.bsc.initFromGCS.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-gcs-creds-init-from"
  labels: {{ include "bsc.labels" . | nindent 4 }}
type: Opaque
data:
  S3_ENDPOINT_URL: {{ .Values.bsc.initFromGCS.endpoint | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.bsc.initFromGCS.keyID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.bsc.initFromGCS.accessKey | b64enc | quote }}
{{- end }}
{{- if .Values.bsc.syncToGCS.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-gcs-creds-sync-to"
  labels: {{ include "bsc.labels" . | nindent 4 }}
type: Opaque
data:
  S3_ENDPOINT_URL: {{ .Values.bsc.syncToGCS.endpoint | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.bsc.syncToGCS.keyID | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.bsc.syncToGCS.accessKey | b64enc | quote }}
{{- end }}
