apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bsc.fullname" . }}
  labels:
{{ include "bsc.labels" . | indent 4 }}
spec:
  serviceName: "{{ .Release.Name }}-service"
  replicas: {{ .Values.replicaCount }} # by default is 1
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bsc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      bsc/chain: {{ .Values.bsc.chain }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bsc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        bsc/chain: {{ .Values.bsc.chain }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.bscCmdOverride }}
        command: [ "{{ .Values.bscCmd }}" ]
        {{- end }}
        args:
          - --config=/config/config.toml
          - --datadir={{ .Values.bsc.base_path }}
          - --syncmode={{ .Values.bsc.syncmode }}
          - --gcmode={{ .Values.bsc.gcmode }}
          - --maxpeers={{ .Values.bsc.maxpeers }}
          - --cache={{ .Values.bsc.cache }}
          - --snapshot=false
          - --port={{ .Values.service.p2pPort0 }}
          - --txlookuplimit=0
          - --cache.preimages
          {{- if and .Values.externalLBp2p .Values.externalLBp2pIP }}
          - --nat=extip:{{- .Values.externalLBp2pIP -}}
          {{- end }}
        workingDir: "{{ .Values.bsc.base_path }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
          {{- range $val := .Values.service.ports }}
        - containerPort: {{ $val.port }}
          {{- if $val.hostPort }}
          hostPort: {{ $val.hostPort }}
          {{- end }}
          name: "{{ $val.name }}"
          protocol: {{ $val.protocol | default "TCP" }}
          {{- end }}
        volumeMounts:
        - name: bsc-config
          mountPath: /config
        - name: scripts
          mountPath: /scripts
        - name: bsc-pvc
          mountPath: {{ .Values.bsc.base_path }}
        {{- if .Values.livenessProbe }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /scripts/check_node_health.sh
            - http://127.0.0.1:{{ .Values.service.rpcPort }}
            - "300"
            - last_synced_block.txt
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - /scripts/check_node_readiness.sh
            - --timestamp-distinct
            - "300"
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
      - name: logger
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "tail","-F","{{ .Values.bsc.base_path }}/bsc.log" ]
        workingDir: "{{ .Values.bsc.base_path }}"
        volumeMounts:
          - name: bsc-pvc
            mountPath: {{ .Values.bsc.base_path }}
            readOnly: true
      {{- if .Values.metrics.enabled }}
      - name: metrics
        image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
        args:
          - -url
          - http://127.0.0.1:{{ .Values.service.rpcPort }}
      {{- end }}
      {{- if .Values.failback.enabled }}
      - name: nginx
        image: "{{ .Values.failback.image.repository }}:{{ .Values.failback.image.tag }}"
        imagePullPolicy: {{ .Values.failback.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.failback.port }}
            name: nginx
            protocol: TCP
        volumeMounts:
          - mountPath: /etc/nginx/
            name: nginx-config-volume
      {{- end }}
      {{- if .Values.failback.metrics.enabled }}
      - name: nginx-metrics
        image: "{{ .Values.failback.metrics.image.repository }}:{{ .Values.failback.metrics.image.tag }}"
        imagePullPolicy: {{ .Values.failback.metrics.image.pullPolicy }}
        args:
          - -nginx.scrape-uri=http://localhost:8000/metrics
        ports:
          - containerPort: {{ .Values.failback.metrics.port }}
            name: {{ .Values.failback.metrics.name }}
            protocol: TCP
      {{- end }}
      {{- if .Values.bxgateway.enabled }}
      - name: bxgateway
        image: "{{ .Values.bxgateway.image.repository }}:{{ .Values.bxgateway.image.tag }}"
        imagePullPolicy: {{ .Values.bxgateway.image.pullPolicy }}
        workingDir: "/app/bxgateway"
        command:
          - "/sbin/tini"
          - "--"
          - "/bin/sh"
          - "-c"
          - "/bin/sh /usr/local/bin/docker-entrypoint.sh --private-ssl-base-url=file:///app/ssl --rpc=True --rpc-host=0.0.0.0 --rpc-port={{ .Values.bxgateway.rpc_port }}
           --ws=True --ws-host=0.0.0.0 --ws-port={{ .Values.bxgateway.ws_port }}
           --blockchain-protocol={{ .Values.bxgateway.blockchain_protocol }}
           --blockchain-network={{ .Values.bxgateway.blockchain_network }}
           --continent={{ .Values.bxgateway.continent }}
           --enode=enode://`cat {{ .Values.bsc.base_path }}/geth/enode`@localhost:30311
           --node-public-key=`cat {{ .Values.bsc.base_path }}/geth/enode`
           --private-key={{ .Values.bxgateway.private_key }}
           --data-dir=/tmp"
        ports:
          - name: rpc
            containerPort: {{ .Values.bxgateway.rpc_port }}
            protocol: TCP
          - name: ws
            containerPort: {{ .Values.bxgateway.ws_port }}
            protocol: TCP
          - name: p2p-tcp
            containerPort: 9001
            protocol: TCP
          - name: p2p-udp
            containerPort: 9001
            protocol: UDP
        volumeMounts:
          - name: bxgateway-certs
            mountPath: /app/ssl/external_gateway/registration_only
          - name: bsc-pvc
            mountPath: {{ .Values.bsc.base_path }}
      {{- end }}
      initContainers:
      - name: remove-lock
        command:
          - rm
          - -f
          - {{ .Values.bsc.base_path }}/geth/LOCK
        image: busybox
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: bsc-pvc
            mountPath: {{ .Values.bsc.base_path }}
      {{- if .Values.nodekey_init.enabled }}
      - name: nodekey-init
        command:
          - sh
          - -c
          - "bootnode -genkey {{ .Values.bsc.base_path }}/geth/nodekey -writeaddress > {{ .Values.bsc.base_path }}/geth/enode"
        image: ethereum/client-go:alltools-latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: bsc-pvc
            mountPath: {{ .Values.bsc.base_path }}
      {{- end }}
      {{- if .Values.init_genesis }}
      - name: init
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c", "wget -O /tmp/mainnet.zip
        https://github.com/binance-chain/bsc/releases/download/{{ $.Chart.AppVersion }}/mainnet.zip &&
        cd /tmp && unzip mainnet.zip &&
        geth --datadir={{ .Values.bsc.base_path }} init /tmp/genesis.json"]
        volumeMounts:
          - name: bsc-pvc
            mountPath: {{ .Values.bsc.base_path }}
      {{- end }}
      volumes:
        - name: bsc-config
          configMap:
            name: "{{ .Release.Name }}-config"
        - name: scripts
          configMap:
            name: "{{ .Release.Name }}-scripts"
        {{- if not .Values.persistence.enabled }}
        - name: bsc-pvc
          emptyDir: {}
        {{- end }}
        {{- if .Values.failback.enabled }}
        - name: nginx-config-volume
          configMap:
            name: "{{ .Release.Name }}-nginx-config"
        {{- end }}
        {{- if .Values.bxgateway.enabled }}
        - name: bxgateway-certs
          secret:
            secretName: "{{ .Release.Name }}-bxgateway-certs"
        {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: bsc-pvc
        labels:
          app: bsc
      spec:
        accessModes:
        - {{.Values.persistence.accessMode }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        volumeMode: Filesystem
  {{- end }}
