apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gcp-local-ssd-raid.fullname" . }}-pv-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "gcp-local-ssd-raid.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:persistent-volume-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gcp-local-ssd-raid.fullname" . }}-node-binding
subjects:
  - kind: ServiceAccount
    name: {{ include "gcp-local-ssd-raid.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "gcp-local-ssd-raid.fullname" . }}-clusterrole
  apiGroup: rbac.authorization.k8s.io
