apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gcp-local-ssd-raid.fullname" . }}-config
data:
  setPVOwnerRef: "true"
  nodeLabelsForPV: |
    - kubernetes.io/hostname
  storageClassMap: |
    local-storage:
      hostDir: /mnt/disks
      mountDir: /mnt/disks
