{{- if .Values.plugins.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "solana.fullname" $ }}-plugins-config
  labels:
    {{- include "solana.labels" . | nindent 4 }}
data:
  {{- if .Values.plugins.yellowstoneGRPC.enabled }}
  yellowstone-grpc-config.json: |-
    {{- .Values.plugins.yellowstoneGRPC.config | nindent 4 }}
  {{- end }}
  {{- if .Values.plugins.jitoGRPC.enabled }}
  jitogrpc-config.json: |-
    {{- .Values.plugins.jitoGRPC.config | nindent 4 }}
  {{- end }}
{{- end }}
